apiVersion: v1
kind: Secret
metadata:
  name: train-service-secrets
type: Opaque
stringData:
  db-host: "postgres"
  db-user: "postgres"
  db-password: "postgres_secure_password"
  redis-host: "redis"
