deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    if: github.event_name == 'push'
    permissions:
      id-token: write # CRITICAL for the OIDC "handshake"
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use the ARN we just registered in the EKS Access Entry
          role-to-assume: arn:aws:iam::965062601731:role/GitHubActionsEKSRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.K8S_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Deploy to Kubernetes
        run: |
          # This command tells Kubernetes to pull the new image you just pushed
          kubectl set image deployment/train-service train-service=${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          # This waits to make sure the app actually starts successfully
          kubectl rollout status deployment/train-service --timeout=120s
